// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clue.sql

package storesqlc

import (
	"context"
	"database/sql"
)

const listFoundClues = `-- name: ListFoundClues :many
SELECT
    id,
    save_id,
    scenario_id,
    description,
    found,
    found_in_location_id,
    found_at_turn
FROM clues
WHERE save_id = ? AND found = 1
ORDER BY found_at_turn
`

func (q *Queries) ListFoundClues(ctx context.Context, saveID string) ([]Clue, error) {
	rows, err := q.db.QueryContext(ctx, listFoundClues, saveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Clue{}
	for rows.Next() {
		var i Clue
		if err := rows.Scan(
			&i.ID,
			&i.SaveID,
			&i.ScenarioID,
			&i.Description,
			&i.Found,
			&i.FoundInLocationID,
			&i.FoundAtTurn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markClueFound = `-- name: MarkClueFound :execrows
UPDATE clues
SET found = 1, found_in_location_id = ?, found_at_turn = ?
WHERE id = ?
`

type MarkClueFoundParams struct {
	FoundInLocationID sql.NullString `json:"found_in_location_id"`
	FoundAtTurn       sql.NullInt64  `json:"found_at_turn"`
	ID                string         `json:"id"`
}

func (q *Queries) MarkClueFound(ctx context.Context, arg MarkClueFoundParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markClueFound, arg.FoundInLocationID, arg.FoundAtTurn, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertClue = `-- name: UpsertClue :exec
INSERT INTO clues (
    id,
    save_id,
    scenario_id,
    description,
    found,
    found_in_location_id,
    found_at_turn
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    save_id = excluded.save_id,
    scenario_id = excluded.scenario_id,
    description = excluded.description,
    found = excluded.found,
    found_in_location_id = excluded.found_in_location_id,
    found_at_turn = excluded.found_at_turn
`

type UpsertClueParams struct {
	ID                string         `json:"id"`
	SaveID            string         `json:"save_id"`
	ScenarioID        string         `json:"scenario_id"`
	Description       string         `json:"description"`
	Found             int64          `json:"found"`
	FoundInLocationID sql.NullString `json:"found_in_location_id"`
	FoundAtTurn       sql.NullInt64  `json:"found_at_turn"`
}

func (q *Queries) UpsertClue(ctx context.Context, arg UpsertClueParams) error {
	_, err := q.db.ExecContext(ctx, upsertClue,
		arg.ID,
		arg.SaveID,
		arg.ScenarioID,
		arg.Description,
		arg.Found,
		arg.FoundInLocationID,
		arg.FoundAtTurn,
	)
	return err
}
