// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package storesqlc

import (
	"context"
)

const appendEvent = `-- name: AppendEvent :execlastid
INSERT INTO events (
    save_id,
    turn,
    type,
    description,
    related_entities_json,
    created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type AppendEventParams struct {
	SaveID              string `json:"save_id"`
	Turn                int64  `json:"turn"`
	Type                string `json:"type"`
	Description         string `json:"description"`
	RelatedEntitiesJson string `json:"related_entities_json"`
	CreatedAt           int64  `json:"created_at"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, appendEvent,
		arg.SaveID,
		arg.Turn,
		arg.Type,
		arg.Description,
		arg.RelatedEntitiesJson,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listEvents = `-- name: ListEvents :many
SELECT
    id,
    save_id,
    turn,
    type,
    description,
    related_entities_json,
    created_at
FROM events
WHERE save_id = ?
  AND (? = 0 OR turn >= ?)
  AND (? = 0 OR turn <= ?)
ORDER BY turn ASC, id ASC
`

type ListEventsParams struct {
	SaveID  string      `json:"save_id"`
	Column2 interface{} `json:"column_2"`
	Turn    int64       `json:"turn"`
	Column4 interface{} `json:"column_4"`
	Turn_2  int64       `json:"turn_2"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.SaveID,
		arg.Column2,
		arg.Turn,
		arg.Column4,
		arg.Turn_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SaveID,
			&i.Turn,
			&i.Type,
			&i.Description,
			&i.RelatedEntitiesJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
