// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investigator.sql

package storesqlc

import (
	"context"
)

const deactivateInvestigator = `-- name: DeactivateInvestigator :execrows
UPDATE investigators
SET active = 0
WHERE id = ?
`

func (q *Queries) DeactivateInvestigator(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deactivateInvestigator, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveInvestigator = `-- name: GetActiveInvestigator :one
SELECT
    id,
    save_id,
    name,
    occupation,
    attrs_json,
    skills_json,
    hp,
    mp,
    san,
    inventory_json,
    active
FROM investigators
WHERE save_id = ? AND active = 1
LIMIT 1
`

func (q *Queries) GetActiveInvestigator(ctx context.Context, saveID string) (Investigator, error) {
	row := q.db.QueryRowContext(ctx, getActiveInvestigator, saveID)
	var i Investigator
	err := row.Scan(
		&i.ID,
		&i.SaveID,
		&i.Name,
		&i.Occupation,
		&i.AttrsJson,
		&i.SkillsJson,
		&i.Hp,
		&i.Mp,
		&i.San,
		&i.InventoryJson,
		&i.Active,
	)
	return i, err
}

const listInvestigators = `-- name: ListInvestigators :many
SELECT
    id,
    save_id,
    name,
    occupation,
    attrs_json,
    skills_json,
    hp,
    mp,
    san,
    inventory_json,
    active
FROM investigators
WHERE save_id = ?
ORDER BY name
`

func (q *Queries) ListInvestigators(ctx context.Context, saveID string) ([]Investigator, error) {
	rows, err := q.db.QueryContext(ctx, listInvestigators, saveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Investigator{}
	for rows.Next() {
		var i Investigator
		if err := rows.Scan(
			&i.ID,
			&i.SaveID,
			&i.Name,
			&i.Occupation,
			&i.AttrsJson,
			&i.SkillsJson,
			&i.Hp,
			&i.Mp,
			&i.San,
			&i.InventoryJson,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvestigatorVitals = `-- name: UpdateInvestigatorVitals :execrows
UPDATE investigators
SET hp = ?, mp = ?, san = ?
WHERE id = ?
`

type UpdateInvestigatorVitalsParams struct {
	Hp  int64  `json:"hp"`
	Mp  int64  `json:"mp"`
	San int64  `json:"san"`
	ID  string `json:"id"`
}

func (q *Queries) UpdateInvestigatorVitals(ctx context.Context, arg UpdateInvestigatorVitalsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateInvestigatorVitals,
		arg.Hp,
		arg.Mp,
		arg.San,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertInvestigator = `-- name: UpsertInvestigator :exec
INSERT INTO investigators (
    id,
    save_id,
    name,
    occupation,
    attrs_json,
    skills_json,
    hp,
    mp,
    san,
    inventory_json,
    active
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    save_id = excluded.save_id,
    name = excluded.name,
    occupation = excluded.occupation,
    attrs_json = excluded.attrs_json,
    skills_json = excluded.skills_json,
    hp = excluded.hp,
    mp = excluded.mp,
    san = excluded.san,
    inventory_json = excluded.inventory_json,
    active = excluded.active
`

type UpsertInvestigatorParams struct {
	ID            string `json:"id"`
	SaveID        string `json:"save_id"`
	Name          string `json:"name"`
	Occupation    string `json:"occupation"`
	AttrsJson     string `json:"attrs_json"`
	SkillsJson    string `json:"skills_json"`
	Hp            int64  `json:"hp"`
	Mp            int64  `json:"mp"`
	San           int64  `json:"san"`
	InventoryJson string `json:"inventory_json"`
	Active        int64  `json:"active"`
}

func (q *Queries) UpsertInvestigator(ctx context.Context, arg UpsertInvestigatorParams) error {
	_, err := q.db.ExecContext(ctx, upsertInvestigator,
		arg.ID,
		arg.SaveID,
		arg.Name,
		arg.Occupation,
		arg.AttrsJson,
		arg.SkillsJson,
		arg.Hp,
		arg.Mp,
		arg.San,
		arg.InventoryJson,
		arg.Active,
	)
	return err
}
