// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item.sql

package storesqlc

import (
	"context"
	"database/sql"
)

const destroyItem = `-- name: DestroyItem :execrows
UPDATE items
SET destroyed = 1
WHERE id = ?
`

func (q *Queries) DestroyItem(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, destroyItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getItem = `-- name: GetItem :one
SELECT
    id,
    save_id,
    name,
    description,
    owner_type,
    owner_id,
    properties_json,
    destroyed
FROM items
WHERE id = ?
`

func (q *Queries) GetItem(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.SaveID,
		&i.Name,
		&i.Description,
		&i.OwnerType,
		&i.OwnerID,
		&i.PropertiesJson,
		&i.Destroyed,
	)
	return i, err
}

const listDestroyedItems = `-- name: ListDestroyedItems :many
SELECT
    id,
    save_id,
    name,
    description,
    owner_type,
    owner_id,
    properties_json,
    destroyed
FROM items
WHERE save_id = ? AND destroyed = 1
ORDER BY name
`

func (q *Queries) ListDestroyedItems(ctx context.Context, saveID string) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listDestroyedItems, saveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.SaveID,
			&i.Name,
			&i.Description,
			&i.OwnerType,
			&i.OwnerID,
			&i.PropertiesJson,
			&i.Destroyed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveItem = `-- name: MoveItem :execrows
UPDATE items
SET owner_type = ?, owner_id = ?
WHERE id = ?
`

type MoveItemParams struct {
	OwnerType string         `json:"owner_type"`
	OwnerID   sql.NullString `json:"owner_id"`
	ID        string         `json:"id"`
}

func (q *Queries) MoveItem(ctx context.Context, arg MoveItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveItem, arg.OwnerType, arg.OwnerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertItem = `-- name: UpsertItem :exec
INSERT INTO items (
    id,
    save_id,
    name,
    description,
    owner_type,
    owner_id,
    properties_json,
    destroyed
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    save_id = excluded.save_id,
    name = excluded.name,
    description = excluded.description,
    owner_type = excluded.owner_type,
    owner_id = excluded.owner_id,
    properties_json = excluded.properties_json,
    destroyed = excluded.destroyed
`

type UpsertItemParams struct {
	ID             string         `json:"id"`
	SaveID         string         `json:"save_id"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	OwnerType      string         `json:"owner_type"`
	OwnerID        sql.NullString `json:"owner_id"`
	PropertiesJson string         `json:"properties_json"`
	Destroyed      int64          `json:"destroyed"`
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertItem,
		arg.ID,
		arg.SaveID,
		arg.Name,
		arg.Description,
		arg.OwnerType,
		arg.OwnerID,
		arg.PropertiesJson,
		arg.Destroyed,
	)
	return err
}
