// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: location.sql

package storesqlc

import (
	"context"
	"database/sql"
)

const getLocation = `-- name: GetLocation :one
SELECT
    id,
    save_id,
    name,
    description,
    parent_id,
    connections_json,
    visited
FROM locations
WHERE id = ?
`

func (q *Queries) GetLocation(ctx context.Context, id string) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.SaveID,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.ConnectionsJson,
		&i.Visited,
	)
	return i, err
}

const markLocationVisited = `-- name: MarkLocationVisited :execrows
UPDATE locations
SET visited = 1
WHERE id = ?
`

func (q *Queries) MarkLocationVisited(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markLocationVisited, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertLocation = `-- name: UpsertLocation :exec
INSERT INTO locations (
    id,
    save_id,
    name,
    description,
    parent_id,
    connections_json,
    visited
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    save_id = excluded.save_id,
    name = excluded.name,
    description = excluded.description,
    parent_id = excluded.parent_id,
    connections_json = excluded.connections_json,
    visited = excluded.visited
`

type UpsertLocationParams struct {
	ID              string         `json:"id"`
	SaveID          string         `json:"save_id"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	ParentID        sql.NullString `json:"parent_id"`
	ConnectionsJson string         `json:"connections_json"`
	Visited         int64          `json:"visited"`
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertLocation,
		arg.ID,
		arg.SaveID,
		arg.Name,
		arg.Description,
		arg.ParentID,
		arg.ConnectionsJson,
		arg.Visited,
	)
	return err
}
