// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storesqlc

import (
	"database/sql"
)

type Clue struct {
	ID                string         `json:"id"`
	SaveID            string         `json:"save_id"`
	ScenarioID        string         `json:"scenario_id"`
	Description       string         `json:"description"`
	Found             int64          `json:"found"`
	FoundInLocationID sql.NullString `json:"found_in_location_id"`
	FoundAtTurn       sql.NullInt64  `json:"found_at_turn"`
}

type Event struct {
	ID                  int64  `json:"id"`
	SaveID              string `json:"save_id"`
	Turn                int64  `json:"turn"`
	Type                string `json:"type"`
	Description         string `json:"description"`
	RelatedEntitiesJson string `json:"related_entities_json"`
	CreatedAt           int64  `json:"created_at"`
}

type Investigator struct {
	ID            string `json:"id"`
	SaveID        string `json:"save_id"`
	Name          string `json:"name"`
	Occupation    string `json:"occupation"`
	AttrsJson     string `json:"attrs_json"`
	SkillsJson    string `json:"skills_json"`
	Hp            int64  `json:"hp"`
	Mp            int64  `json:"mp"`
	San           int64  `json:"san"`
	InventoryJson string `json:"inventory_json"`
	Active        int64  `json:"active"`
}

type Item struct {
	ID             string         `json:"id"`
	SaveID         string         `json:"save_id"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	OwnerType      string         `json:"owner_type"`
	OwnerID        sql.NullString `json:"owner_id"`
	PropertiesJson string         `json:"properties_json"`
	Destroyed      int64          `json:"destroyed"`
}

type Location struct {
	ID              string         `json:"id"`
	SaveID          string         `json:"save_id"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	ParentID        sql.NullString `json:"parent_id"`
	ConnectionsJson string         `json:"connections_json"`
	Visited         int64          `json:"visited"`
}

type NPC struct {
	ID               string         `json:"id"`
	SaveID           string         `json:"save_id"`
	Name             string         `json:"name"`
	Personality      string         `json:"personality"`
	KnowledgeJson    string         `json:"knowledge_json"`
	RelationToPlayer int64          `json:"relation_to_player"`
	LocationID       sql.NullString `json:"location_id"`
	Alive            int64          `json:"alive"`
}

type Save struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	ScenarioID        string         `json:"scenario_id"`
	CurrentLocationID sql.NullString `json:"current_location_id"`
	TurnCount         int64          `json:"turn_count"`
	TimeOfDay         string         `json:"time_of_day"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
	VariantID         string         `json:"variant_id"`
}
