// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: npc.sql

package storesqlc

import (
	"context"
	"database/sql"
)

const getNPC = `-- name: GetNPC :one
SELECT
    id,
    save_id,
    name,
    personality,
    knowledge_json,
    relation_to_player,
    location_id,
    alive
FROM npcs
WHERE id = ?
`

func (q *Queries) GetNPC(ctx context.Context, id string) (Npc, error) {
	row := q.db.QueryRowContext(ctx, getNPC, id)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.SaveID,
		&i.Name,
		&i.Personality,
		&i.KnowledgeJson,
		&i.RelationToPlayer,
		&i.LocationID,
		&i.Alive,
	)
	return i, err
}

const killNPC = `-- name: KillNPC :execrows
UPDATE npcs
SET alive = 0
WHERE id = ?
`

func (q *Queries) KillNPC(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, killNPC, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listNPCsAtLocation = `-- name: ListNPCsAtLocation :many
SELECT
    id,
    save_id,
    name,
    personality,
    knowledge_json,
    relation_to_player,
    location_id,
    alive
FROM npcs
WHERE save_id = ? AND location_id = ? AND alive = 1
ORDER BY name
`

type ListNPCsAtLocationParams struct {
	SaveID     string         `json:"save_id"`
	LocationID sql.NullString `json:"location_id"`
}

func (q *Queries) ListNPCsAtLocation(ctx context.Context, arg ListNPCsAtLocationParams) ([]Npc, error) {
	rows, err := q.db.QueryContext(ctx, listNPCsAtLocation, arg.SaveID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Npc{}
	for rows.Next() {
		var i Npc
		if err := rows.Scan(
			&i.ID,
			&i.SaveID,
			&i.Name,
			&i.Personality,
			&i.KnowledgeJson,
			&i.RelationToPlayer,
			&i.LocationID,
			&i.Alive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNPCRelation = `-- name: UpdateNPCRelation :execrows
UPDATE npcs
SET relation_to_player = relation_to_player + ?
WHERE id = ?
`

type UpdateNPCRelationParams struct {
	RelationToPlayer int64  `json:"relation_to_player"`
	ID               string `json:"id"`
}

func (q *Queries) UpdateNPCRelation(ctx context.Context, arg UpdateNPCRelationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNPCRelation, arg.RelationToPlayer, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertNPC = `-- name: UpsertNPC :exec
INSERT INTO npcs (
    id,
    save_id,
    name,
    personality,
    knowledge_json,
    relation_to_player,
    location_id,
    alive
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    save_id = excluded.save_id,
    name = excluded.name,
    personality = excluded.personality,
    knowledge_json = excluded.knowledge_json,
    relation_to_player = excluded.relation_to_player,
    location_id = excluded.location_id,
    alive = excluded.alive
`

type UpsertNPCParams struct {
	ID               string         `json:"id"`
	SaveID           string         `json:"save_id"`
	Name             string         `json:"name"`
	Personality      string         `json:"personality"`
	KnowledgeJson    string         `json:"knowledge_json"`
	RelationToPlayer int64          `json:"relation_to_player"`
	LocationID       sql.NullString `json:"location_id"`
	Alive            int64          `json:"alive"`
}

func (q *Queries) UpsertNPC(ctx context.Context, arg UpsertNPCParams) error {
	_, err := q.db.ExecContext(ctx, upsertNPC,
		arg.ID,
		arg.SaveID,
		arg.Name,
		arg.Personality,
		arg.KnowledgeJson,
		arg.RelationToPlayer,
		arg.LocationID,
		arg.Alive,
	)
	return err
}
