// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: save.sql

package storesqlc

import (
	"context"
	"database/sql"
)

const createSave = `-- name: CreateSave :exec
INSERT INTO saves (
    id,
    name,
    scenario_id,
    variant_id,
    current_location_id,
    turn_count,
    time_of_day,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSaveParams struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	ScenarioID        string         `json:"scenario_id"`
	VariantID         string         `json:"variant_id"`
	CurrentLocationID sql.NullString `json:"current_location_id"`
	TurnCount         int64          `json:"turn_count"`
	TimeOfDay         string         `json:"time_of_day"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

func (q *Queries) CreateSave(ctx context.Context, arg CreateSaveParams) error {
	_, err := q.db.ExecContext(ctx, createSave,
		arg.ID,
		arg.Name,
		arg.ScenarioID,
		arg.VariantID,
		arg.CurrentLocationID,
		arg.TurnCount,
		arg.TimeOfDay,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSave = `-- name: DeleteSave :execrows
DELETE FROM saves
WHERE id = ?
`

func (q *Queries) DeleteSave(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSave, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSave = `-- name: GetSave :one
SELECT id, name, scenario_id, current_location_id, turn_count, time_of_day, created_at, updated_at, variant_id
FROM saves
WHERE id = ?
`

func (q *Queries) GetSave(ctx context.Context, id string) (Save, error) {
	row := q.db.QueryRowContext(ctx, getSave, id)
	var i Save
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ScenarioID,
		&i.CurrentLocationID,
		&i.TurnCount,
		&i.TimeOfDay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VariantID,
	)
	return i, err
}

const listSaves = `-- name: ListSaves :many
SELECT id, name, scenario_id, current_location_id, turn_count, time_of_day, created_at, updated_at, variant_id
FROM saves
ORDER BY updated_at DESC
`

func (q *Queries) ListSaves(ctx context.Context) ([]Save, error) {
	rows, err := q.db.QueryContext(ctx, listSaves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Save{}
	for rows.Next() {
		var i Save
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ScenarioID,
			&i.CurrentLocationID,
			&i.TurnCount,
			&i.TimeOfDay,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VariantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTimeOfDay = `-- name: SetTimeOfDay :execrows
UPDATE saves
SET time_of_day = ?, updated_at = ?
WHERE id = ?
`

type SetTimeOfDayParams struct {
	TimeOfDay string `json:"time_of_day"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) SetTimeOfDay(ctx context.Context, arg SetTimeOfDayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTimeOfDay, arg.TimeOfDay, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSaveProgress = `-- name: UpdateSaveProgress :execrows
UPDATE saves
SET current_location_id = ?, turn_count = ?, updated_at = ?
WHERE id = ?
`

type UpdateSaveProgressParams struct {
	CurrentLocationID sql.NullString `json:"current_location_id"`
	TurnCount         int64          `json:"turn_count"`
	UpdatedAt         int64          `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateSaveProgress(ctx context.Context, arg UpdateSaveProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSaveProgress,
		arg.CurrentLocationID,
		arg.TurnCount,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
