package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/zhuzhenwu/whisperer/internal/config"
	"github.com/zhuzhenwu/whisperer/internal/i18n"
)

// wizardEnv 把所有外部依赖（提示输出、用户输入、退出码）抽进结构体，方便测试
// 注入 stub。生产路径在 runWizard 调用 newWizardEnv() 时绑定 stdin / stderr。
type wizardEnv struct {
	in  *bufio.Reader
	out io.Writer
	tr  *i18n.Translator
}

func newWizardEnv(tr *i18n.Translator) *wizardEnv {
	return &wizardEnv{
		in:  bufio.NewReader(os.Stdin),
		out: os.Stderr,
		tr:  tr,
	}
}

// wizardResult 是向导收集到的偏好。空字段 → 用户跳过 / 接受默认。
type wizardResult struct {
	Provider  string
	APIKey    string // 仅返回给调用方做提示，不写文件
	APIKeyEnv string // 提示用户该把 key 放到哪个环境变量
	Scenario  string
	Lang      string // "auto" / "en" / "zh-CN"
}

// runWizard 是首次运行 / `whisperer init` 路径。
//
//   - configPath 是最终落盘路径
//   - tr 是已初始化的 i18n.Translator
//
// 返回：
//   - written: 是否真的把 config 写盘（用户可能在确认环节选 n）
//   - result:  收集到的偏好（即使没写盘也返回，便于把 key 提示打出来）
//   - err:     I/O 类失败
func runWizard(env *wizardEnv, configPath string) (written bool, result wizardResult, err error) {
	tr := env.tr

	// === Welcome ===
	env.println()
	env.println(tr.T("wizard.welcome_title"))
	env.println(strings.Repeat("─", 32))
	env.println(tr.T("wizard.welcome_body", map[string]any{"Path": configPath}))
	env.println()

	// === 1. provider ===
	for {
		env.println(tr.T("wizard.choose_provider"))
		_, _ = fmt.Fprint(env.out, "> ")
		choice, err := env.readLine()
		if err != nil {
			return false, result, err
		}
		choice = strings.ToLower(strings.TrimSpace(choice))
		switch choice {
		case "", "anthropic":
			result.Provider = "anthropic"
			result.APIKeyEnv = "ANTHROPIC_API_KEY"
		case "openrouter", "or":
			result.Provider = "openrouter"
			result.APIKeyEnv = "OPENROUTER_API_KEY"
		default:
			env.println(tr.T("wizard.choose_provider_invalid", map[string]any{"Choice": choice}))
			continue
		}
		break
	}
	env.println()

	// === 2. API key ===
	env.println(tr.T("wizard.api_key_prompt", map[string]any{"EnvVar": result.APIKeyEnv}))
	_, _ = fmt.Fprint(env.out, "> ")
	keyLine, err := env.readLine()
	if err != nil {
		return false, result, err
	}
	result.APIKey = strings.TrimSpace(keyLine)
	if result.APIKey == "" {
		env.println(tr.T("wizard.api_key_blank_warning", map[string]any{"EnvVar": result.APIKeyEnv}))
	}
	env.println()

	// === 3. scenario ===
	for {
		env.println(tr.T("wizard.choose_scenario"))
		_, _ = fmt.Fprint(env.out, "> ")
		choice, err := env.readLine()
		if err != nil {
			return false, result, err
		}
		choice = strings.TrimSpace(choice)
		if choice == "" {
			result.Scenario = "fog_harbor"
			break
		}
		// 内置目前只有 fog_harbor；自定义剧本走热加载（Phase 2.5）。
		if choice == "fog_harbor" {
			result.Scenario = choice
			break
		}
		hotloadDir := scenarioHotloadDir()
		env.println(tr.T("wizard.choose_scenario_invalid", map[string]any{
			"Choice":     choice,
			"HotloadDir": hotloadDir,
		}))
	}
	env.println()

	// === 4. language ===
	env.println(tr.T("wizard.choose_lang"))
	_, _ = fmt.Fprint(env.out, "> ")
	langChoice, err := env.readLine()
	if err != nil {
		return false, result, err
	}
	switch strings.ToLower(strings.TrimSpace(langChoice)) {
	case "", "auto":
		result.Lang = "" // 留空 → 运行时自动检测
	case "en":
		result.Lang = "en"
	case "zh-cn", "zh", "cn":
		result.Lang = "zh-CN"
	default:
		// 任何其他用户认可的 BCP47 tag 直接保存
		result.Lang = strings.TrimSpace(langChoice)
	}
	env.println()

	// === 5. confirm ===
	env.println(tr.T("wizard.confirm", map[string]any{"Path": configPath}))
	_, _ = fmt.Fprint(env.out, "> ")
	yn, err := env.readLine()
	if err != nil {
		return false, result, err
	}
	yn = strings.ToLower(strings.TrimSpace(yn))
	if yn == "n" || yn == "no" {
		env.println(tr.T("wizard.aborted"))
		return false, result, nil
	}

	// === 6. write ===
	if err := writeWizardConfig(configPath, result); err != nil {
		return false, result, err
	}
	env.println(tr.T("wizard.written", map[string]any{"Path": configPath}))
	if result.APIKey == "" {
		env.println(tr.T("wizard.api_key_hint"))
	}
	return true, result, nil
}

// readLine 读 stdin 一行；EOF 视作空字符串（让向导在 piped 输入下也能退出干净）。
func (e *wizardEnv) readLine() (string, error) {
	line, err := e.in.ReadString('\n')
	if err != nil && err != io.EOF {
		return "", err
	}
	return strings.TrimRight(line, "\r\n"), nil
}

// printf / println 把 fmt.Fprint(ln) 的 error 返回值统一吞掉。终端 UI 写入失败
// 没有合理的恢复路径——继续走流程让 readLine 兜底比反复检查噪音少。
func (e *wizardEnv) println(args ...any) {
	_, _ = fmt.Fprintln(e.out, args...)
}

// writeWizardConfig 把向导收集的偏好写到 path（TOML 格式）。
//
// 注意：API key 严禁写盘——只通过环境变量提供。这里只写 provider / scenario /
// lang 三项，其他保持注释 / 空，让用户自行编辑 example-config.toml 风格。
func writeWizardConfig(path string, r wizardResult) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	var b strings.Builder
	b.WriteString("# Generated by `whisperer init`. Edit freely.\n")
	b.WriteString("# API keys are intentionally NOT stored here — use the environment\n")
	b.WriteString("# variable shown when you ran the wizard, or `--api-key`.\n\n")
	fmt.Fprintf(&b, "provider = %q\n", r.Provider)
	fmt.Fprintf(&b, "scenario = %q\n", r.Scenario)
	if r.Lang != "" {
		fmt.Fprintf(&b, "lang = %q\n", r.Lang)
	}
	// log defaults
	b.WriteString("log_format = \"text\"\n")
	b.WriteString("log_level  = \"info\"\n")
	b.WriteString("# See docs/example-config.toml for model / embedder / timeout knobs.\n")
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("rename %s: %w", path, err)
	}
	return nil
}

// scenarioHotloadDir 返回 Phase 2.5 计划的剧本热加载目录（即使该 feature 还没写
// 完，也可以提前在向导文案里告诉用户）。
func scenarioHotloadDir() string {
	if x := os.Getenv("XDG_CONFIG_HOME"); x != "" {
		return filepath.Join(x, "whisperer", "scenarios")
	}
	if app := os.Getenv("APPDATA"); app != "" {
		return filepath.Join(app, "whisperer", "scenarios")
	}
	if home, err := os.UserHomeDir(); err == nil {
		return filepath.Join(home, ".config", "whisperer", "scenarios")
	}
	return "$HOME/.config/whisperer/scenarios"
}

// shouldRunWizard 决定是否在 main 启动时自动跑向导。规则：
//   - 用户传了 init 子命令 → 必跑
//   - configPath 文件存在 → 不跑
//   - stdin 不是 tty（脚本/重定向） → 不跑（避免阻塞 CI）
//   - 否则 → 跑
func shouldRunWizard(args []string, configPath string) bool {
	for _, a := range args {
		if a == "init" {
			return true
		}
	}
	if _, err := os.Stat(configPath); err == nil {
		return false
	}
	if !stdinIsTTY() {
		return false
	}
	return true
}

// stdinIsTTY 判断 stdin 是否连到了交互式终端。简单实现：检查 mode 是否含
// CharDevice。
func stdinIsTTY() bool {
	fi, err := os.Stdin.Stat()
	if err != nil {
		return false
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}

// resolveWizardConfigPath 返回向导要落盘的路径——优先用 --config flag 给的路径，
// 否则走 config.DefaultPath()。空时返回 "" 由调用方处理。
func resolveWizardConfigPath(explicit string) string {
	if explicit != "" {
		return explicit
	}
	return config.DefaultPath()
}
